# Author Dr. Faisal Bukhari, Department of Data Science, FCIT, PU, Lahore, Pakistan

## Numpy
## Numpy is the core library for scientific computing in Python. 
## It provides a high-performance multidimensional array object, and tools for working with these arrays. 

## SciPy is an Open Source Python-based library, which is used in mathematics, scientific computing, Engineering, and technical computing. SciPy also pronounced as "Sigh Pi."

# Numpy VS SciPy
Numpy:

Numpy is written in C and use for mathematical or numeric calculation.
It is faster than other Python Libraries
Numpy is the most useful library for Data Science to perform basic calculations.
Numpy contains nothing but array data type which performs the most basic operation like sorting, shaping, indexing, etc.

SciPy:
SciPy is built in top of the NumPy
SciPy is a fully-featured version of Linear Algebra while Numpy contains only a few features.
Most new Data Science features are available in Scipy rather than Numpy.

Reference: https://www.guru99.com/scipy-tutorial.html

scipy.stats.sem
scipy.stats.sem(a, axis=0, ddof=1)[source]
Calculates the standard error of the mean (or standard error of measurement) of the values in the input array.

Parameters:	
a : array_like

An array containing the values for which the standard error is returned.

axis : int or None, optional.

If axis is None, ravel a first. If axis is an integer, this will be the axis over which to operate. Defaults to 0.

ddof : int, optional

Delta degrees-of-freedom. How many degrees of freedom to adjust for bias in limited samples relative to the population estimate of variance. Defaults to 1.

Returns:	
s : ndarray or float

The standard error of the mean in the sample(s), along the input axis.

Notes

The default value for ddof is different to the default (0) used by other ddof containing routines, such as np.std nd stats.nanstd.
### Reference: https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.sem.html

# Example: The contents of seven similar containers of sulfuric acid are 9.8, 10.2, 10.4, 9.8, 10.0, 10.2, and 9.6 liters. Find a 95% confidence interval for the mean contents of all such containers, assuming an approximately normal distribution.


In [2]:
from scipy import stats
import numpy as np

arr = [9.8, 10.2, 10.4, 9.8, 10.0, 10.2, 9.6]  # data
alpha = 0.05                # significance level = 5%
df = len(arr) - 1           # degress of freedom = 6
t = stats.t.ppf(1 - alpha/2, df) # t-critical value for 95% CI = 2.447
print(round(t,3))

s = np.std(arr, ddof=1) # sample standard deviation = 0.2828
print(round(s,4))
n = len(arr)

lower = np.mean(arr) - (t * s / np.sqrt(n))
print(round(lower,4))
upper = np.mean(arr) + (t * s / np.sqrt(n))
print(round(upper,4))
(lower, upper)


2.447
0.2828
9.7384
10.2616


(9.738414120176683, 10.261585879823317)

In [3]:
#stats.t.interval(1 - alpha, len(arr) - 1, loc=np.mean(arr), scale=stats.sem(arr))

from scipy import stats
import numpy as np
alpha = 0.05                       # significance level = 5%
arr = [9.8, 10.2, 10.4, 9.8, 10.0, 10.2, 9.6]
df = len(arr) - 1                  # degress of freedom = 6

stats.t.interval(1 - alpha, len(arr) - 1, loc=np.mean(arr), scale=stats.sem(arr))


(9.738414120176683, 10.261585879823317)

# Exercise 9.40: In a study conducted at Virginia Tech on the development of ectomycorrhizal, a symbiotic relationship between the roots of trees and a fungus, in which minerals are transferred from the fungus to the trees and sugars from the trees to the fungus, 20 northern red oak seedlings exposed to the fungus Pisolithus tinctorus were grown in a greenhouse. All seedlings were planted in the same type of soil and received the same amount of sunshine and water. Half received no nitrogen at planting time, to serve as a control, and the other half received 368 ppm of nitrogen in the form NaNO3. The stem weights, in grams, at the end of 140 days were recorded as follows:
No Nitrogen     Nitrogen
0.32            0.26
0.53            0.43
0.28            0.47
0.37            0.49
0.47            0.52
0.43            0.75
0.36            0.79
0.42            0.86
0.38            0.62
0.43            0.46
# Construct a 95% confidence interval for the difference in the mean stem weight between seedlings that receive no nitrogen and those that receive 368 ppm of nitrogen. Assume the populations to be normally distributed with equal variances.

In [4]:
x1 = [0.32, 0.53, 0.28, 0.37, 0.47, 0.43, 0.36, 0.42, 0.38, 0.43]
x2 = [0.26, 0.43, 0.47, 0.49, 0.52, 0.75, 0.79, 0.86, 0.62, 0.46]
print(np.mean(x1))
print(np.mean(x2))

alpha = 0.05                                                     # significance level = 5%
n1, n2 = len(x1), len(x2)                                        # sample sizes
var1, var2 = np.var(x1, ddof = 1), np.var(x2, ddof = 1)          # sample variances
sp = np.sqrt(((n1 - 1) * var1 + (n2 - 1) * var2) / (n1 + n2 - 2)) # pooled standard deviation
print("sp =", sp)
df = n1 + n2 - 2                                                 # degrees of freedom
t = stats.t.ppf(1 - alpha/2, df)                                 # t-critical value for 95% CI
print("tabulated", round(t,4))
t_cal = (np.mean(x1) - np.mean(x2))/(sp * np.sqrt(1 / len(x1) + 1 / len(x2)))
print("t calulated:", round(t_cal,4))

lower = (np.mean(x1) - np.mean(x2)) - t * sp * np.sqrt(1 / len(x1) + 1 / len(x2)) 
upper = (np.mean(x1) - np.mean(x2)) + t  * sp * np.sqrt(1 / len(x1) + 1 / len(x2)) 
(lower, upper)

lower = (np.mean(x2) - np.mean(x1)) - t * sp * np.sqrt(1 / len(x1) + 1 / len(x2)) 
upper = (np.mean(x2) - np.mean(x1)) + t * sp * np.sqrt(1 / len(x1) + 1 / len(x2)) 
(lower, upper)

stats.ttest_ind(x1, x2, equal_var=False)


0.39899999999999997
0.5650000000000001
sp = 0.14172351800444255
tabulated 2.1009
t calulated: -2.6191


Ttest_indResult(statistic=-2.6190944840455472, pvalue=0.022863946155002354)

In [5]:


alpha = 0.10                                                     # significance level = 5%
n1, n2 = 12, 10                                                  # sample sizes
s1, s2 = 0.771*0.771, 0.448*0.448             # sample variances
print(s1)
print(s2)
sp = np.sqrt(((n1 - 1) * s1 + (n2 - 1) * s2) / (n1 + n2 - 2))     # pooled standard deviation
print(s)
df = n1 + n2 - 2                                                 # degrees of freedom
print(df)
t = stats.t.ppf(1 - alpha/2, df)                                 # t-critical value for 95% CI
print(t)

lower = (3.11 - 2.04) - t * sp * np.sqrt(1 / n1 + 1 / n2 )
upper = (3.11 - 2.04) + t * sp * np.sqrt(1 / n1 + 1 / n2 )
round(lower,4), round(upper,4)

0.594441
0.20070400000000002
0.28284271247461884
20
1.7247182429207857


(0.593, 1.547)

In [ ]:
# 9.46 The following data represent the running times of films produced by two motion-picture companies.
Company Time (minutes)
I 103 94 110 87 98
II 97 82 123 92 175 88 118
Compute a 90% confidence interval for the difference between the average running times of films produced by
the two companies. Assume that the running-time differences are approximately normally distributed with unequal variances.

In [19]:
from scipy import stats
import numpy as np
x1 = [103, 94, 110, 87, 98]
x2 = [97, 82, 123, 92, 175, 88, 118]
alpha = 0.10                                                       # significance level = 5%
n1 = len(x1)                                                       # sample size
n2 = len(x2)                                                       # sample size
var1 = np.var(x1, ddof=1)                                          # sample variance
var2 = np.var(x2, ddof=1)  
# sample variance
print("Variance:", round(var1,4))
print("Variance:", round(var2,4))
print("Sd:", round(np.sqrt(var1),4))
print("Sd:", round(np.sqrt(var2),4))
s = np.sqrt(var1/n1 + var2/n2)                                     # combined standard deviation
print(round(s,4))

df = (var1/n1 + var2/n2)**2 / ((var1/n1)**2/(n1-1) + (var2/n2)**2/(n2-1))  # degrees of freedom
print("df=",round(df, 0))

t = stats.t.ppf(1 - alpha/2, df)                                   # t-critical value for 95% CI
print("t tabulated:", round(t,4))

print("mean 1 = ", np.mean(x1))
print("mean 2 = ",np.mean(x2))

lower = (np.mean(x2) - np.mean(x1)) - t  * s
upper = (np.mean(x2) - np.mean(x1)) + t  * s
print(round(lower,4), round(upper,4))
lower = (np.mean(x1) - np.mean(x2)) - t  * s
upper = (np.mean(x1) - np.mean(x2)) + t  * s
print(round(lower,4), round(upper,4))
mu1 = 0
mu2 = 0
tcal = ((np.mean(x2) - np.mean(x1)) - (mu1 - mu2))/np.sqrt(var1/n1 + var2/n2)

print("t calulated:", round(tcal,4))

Variance: 76.3
Variance: 1035.9048
Sd: 8.735
Sd: 32.1855
12.7768
df= 7.0
t tabulated: 1.8872
mean 1 =  98.4
mean 2 =  110.71428571428571
-11.7981 36.4267
-36.4267 11.7981
t calulated: 0.9638


# 9.46 The following data represent the running times of films produced by two motion-picture companies.
Company Time (minutes)
I 103 94 110 87 98
II 97 82 123 92 175 88 118
Compute a 90% confidence interval for the difference between the average running times of films produced by
the two companies. Assume that the running-time differences are approximately normally distributed with equal variances.

In [26]:
from scipy import stats
import numpy as np
x1 = [103, 94, 110, 87, 98]
x2 = [97, 82, 123, 92, 175, 88, 118]

print(np.mean(x1))
print(np.mean(x2))

alpha = 0.10                                                     # significance level = 5%
n1, n2 = len(x1), len(x2)                                        # sample sizes
var1, var2 = np.var(x1, ddof = 1), np.var(x2, ddof = 1)          # sample variances
sp = np.sqrt(((n1 - 1) * var1 + (n2 - 1) * var2) / (n1 + n2 - 2)) # pooled standard deviation
print("sp = ", round(sp,4))
df = n1 + n2 - 2                                                 # degrees of freedom
print("df = ",df)
t = stats.t.ppf(1 - alpha/2, df)                                 # t-critical value for 95% CI
print("t-tabulated = ",round(t,4))
t_cal = (np.mean(x2) - np.mean(x1))/(sp * np.sqrt(1 / len(x1) + 1 / len(x2)))
print("t-cal = ",round(t_cal,4))
lower = (np.mean(x1) - np.mean(x2)) - t * sp * np.sqrt(1 / len(x1) + 1 / len(x2)) 
upper = (np.mean(x1) - np.mean(x2)) + t  * sp * np.sqrt(1 / len(x1) + 1 / len(x2)) 
(lower, upper)

lower = (np.mean(x2) - np.mean(x1)) - t * sp * np.sqrt(1 / len(x1) + 1 / len(x2)) 
upper = (np.mean(x2) - np.mean(x1)) + t * sp * np.sqrt(1 / len(x1) + 1 / len(x2)) 
(round(lower,4), round(upper,4))

98.4
110.71428571428571
sp =  25.5355
df =  10
t-tabulated =  1.8125
t-cal =  0.8236


(-14.7858, 39.4143)

In [23]:
from scipy import stats
import numpy as np
a = np.arange(15).reshape(5,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [31]:
stats.sem(a, axis=None, ddof=1)


0.10690449676496969

In [33]:
# 9.8, 10.2, 10.4, 9.8, 10.0, 10.2, and 9.6 
a=[9.8, 10.2, 10.4, 9.8, 10.0, 10.2, 9.6]
stats.sem(a, axis=None, ddof=6)



0.2618614682831907

In [36]:
import numpy as np
a=[9.8, 10.2, 10.4, 9.8, 10.0, 10.2, 9.6]
# np.std(a, axis=None, dtype=None, out=None, ddof=1)
std_err = np.std(a,ddof=1)
print(round(std_err,4))


0.2828


In [29]:
from scipy.stats import sem, t
from scipy import mean
confidence = 0.95
data = [9.8, 10.2, 10.4, 9.8, 10.0, 10.2, 9.6]
std_err = sem(data)
print(std_err)


0.10690449676496969


In [5]:
from scipy.stats import sem, t
from scipy import mean

confidence = 0.95
data = [1, 2, 3, 4, 5]
n = len(data)
m = mean(data)
std_err = sem(data)

h = std_err * t.ppf((1 + confidence) / 2, n - 1)
start = m - h

print(start)

1.036756838522439


In [6]:
end = m + h
print (end)

4.9632431614775605


# Example 6.11: The average zinc concentration recovered from a sample of measurements taken in 36 different locations in a river is found to be 2.6 grams per milliliter. Find the 95% and 99% confidence intervals for the mean zinc concentration in the river. Assume that the population standard deviation is 0.3 gram per milliliter.

In [123]:
from scipy.stats import norm
import numpy as np
ztab = round(norm.ppf(0.975), 2)  #95% confidence interal i.e. 1 - alplh/2 = 0.975
print(ztab)
#ztab = round(norm.ppf(0.995), 4)  #99% confidence interal i.e. 1 - alplh/2 = 0.995
#print(ztab)

sigma = 0.3                       
n = 36
meanx = 2.6
print(ztab * sigma / np.sqrt(n))
lower = meanx  - ztab * sigma / np.sqrt(n)
print(round(lower,4))
upper = meanx  + ztab * sigma / np.sqrt(n)
print(round(upper,4))
(lower, upper)

1.96
0.09799999999999999
2.502
2.698


(2.5020000000000002, 2.698)

In [119]:
from scipy.stats import norm
import numpy as np

ztab = round(norm.ppf(0.995), 4)  #99% confidence interal i.e. 1 - alplh/2 = 0.995
print(ztab)

sigma = 0.30                       
n = 36
meanx = 2.6
lower = meanx  - (ztab * sigma / np.sqrt(n))
print(round(lower,4))
upper = meanx  + (ztab * sigma / np.sqrt(n))
print(round(upper,4))
(lower, upper)

2.5758
2.4712
2.7288


(2.47121, 2.72879)

In [120]:
from scipy.stats import norm
import numpy as np
ztab = round(norm.ppf(0.975), 4)  #95% confidence interal
print(ztab)
ztab = round(norm.ppf(0.995), 4)  #99% confidence interal
print(ztab)
ztab = round(norm.ppf(0.95), 4)  #90% confidence interal
print(ztab)

1.96
2.5758
1.6449


In [6]:
from scipy.stats import norm
import numpy as np
ztab = round(norm.cdf(0.6250), 4)  #90% confidence interal
print(ztab)

0.734


In [11]:
from scipy.stats import norm
import numpy as np
alpha = 0.375
ztab = round(norm.ppf(1 - alpha/), 4)  #90% confidence interal
print(ztab)

-0.8871


In [14]:
import scipy.stats as stats
zvalue = stats.norm.ppf(0.8) #0.8 = area to left

#print corresponding zvalue
print(round(zvalue, 4))

0.8416


In [17]:
import scipy.stats as stats
mean = 40
sd = 6
z = stats.norm.ppf(0.8) #0.8 = area to left
x = sd *z + mean
print(round(x,4))

45.0497


In [19]:
import scipy.stats as stats
mean = 40
sd = 6
z = stats.norm.ppf(0.20)                                           #0.8 = area to left
p20 = sd *z + mean
print(round(p20, 4))



34.9503


In [5]:
from scipy import stats
df = 9
alpha = .05
t = stats.t.ppf(alpha, df) 
print(round(t,4))

-1.8331


In [7]:
from scipy.stats import norm
import numpy as np
alpha = 0.375
ztab = 1-round(norm.ppf(0.63), 4)  #90% confidence interal
print(ztab)

0.6681


In [8]:
import scipy.stats
scipy.stats.norm(loc=100, scale=12)
#where loc is the mean and scale is the std dev
#if you wish to pull out a random number from your distribution
scipy.stats.norm.rvs(loc=100, scale=12)

#To find the probability that the variable has a value LESS than or equal
#let's say 113, you'd use CDF cumulative Density Function
scipy.stats.norm.cdf(113,100,12)
Output: 0.86066975255037792
#or 86.07% probability

#To find the probability that the variable has a value GREATER than or
#equal to let's say 125, you'd use SF Survival Function 
scipy.stats.norm.sf(125,100,12)
Output: 0.018610425189886332
#or 1.86%

#To find the variate for which the probability is given, let's say the 
#value which needed to provide a 98% probability, you'd use the 
#PPF Percent Point Function
scipy.stats.norm.ppf(.98,100,12)
Output: 124.64498692758187

In [11]:
import scipy.stats as stats
prob = round(stats.norm.cdf(45,40,8),4)   # x, mean, sd
print(prob)

0.734
