<a href="https://colab.research.google.com/github/shumyyla/test/blob/master/advance_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
mylist = [5, 7, 2, 6, 9]

map_object = map(lambda x: x ** 2 , mylist)

mylist_squared = list(map_object)

print("Original list: ", mylist)
print("List with items squared: ", mylist_squared)

Original list:  [5, 7, 2, 6, 9]
List with items squared:  [25, 49, 4, 36, 81]


In [ ]:
list1 = [1, 5, 3]
list2 = [4, 2, 3]

In [ ]:
newlist = []

In [ ]:
new  = map(lambda a,b:a**b,list1,list2)

In [ ]:
mnew = list(new)

In [ ]:
mnew

[1, 25, 27]

In [ ]:
listt = [3,4,5,6,7]

new = [i**3 for i in listt]

In [ ]:
new

[27, 64, 125, 216, 343]

In [ ]:
mylist = [1,2,3,6,74, 85, 14, 23, 56, 32, 45 ]

map_object = map(lambda num: num%5, mylist)

remainders = list(map_object)

print("Original list: ", mylist)
print("List of remainders: ", remainders)

Original list:  [1, 2, 3, 6, 74, 85, 14, 23, 56, 32, 45]
List of remainders:  [1, 2, 3, 1, 4, 0, 4, 3, 1, 2, 0]


In [ ]:
mylist = [1,2,3,4,[], {},False , None, 4 , None]

f = filter(None,mylist)

In [ ]:
list(f)

[1, 2, 3, 4, 4]

In [ ]:
mylist = [2,3,4,4,5,55,6,6,60]

f = filter(lambda x: x%2==0,mylist)

list(f)

[2, 4, 4, 6, 6, 60]

In [ ]:
c = ['z','s','a','f','t','t','w','u']

v = ['a','e', 'i','o','u']

In [ ]:
y = filter(lambda x:x in v,c)

In [ ]:
list(y)

['a', 'u']

In [ ]:
from functools import reduce

In [ ]:
def myadd(a,b):
  return a+b

In [ ]:
no = [3,4,5,6,1,2]

a = reduce(myadd, no)

In [ ]:
a

21

In [ ]:
x = reduce(lambda x,y: x*y, no)

In [ ]:
x

720

In [ ]:
l = [2,4,5,7,4,3,2,13,3,5,5,6,6,6,633,3,3,3,3]

In [ ]:
c = reduce(lambda a,b: a if a>b else b, l)

In [ ]:
c

633

In [ ]:
l = [-6,-8,-90,-5,-7]
c = reduce(lambda a,b: a if a>b else b, l, 0)

In [ ]:
c

0

In [ ]:
mylist = [0, 0, 1, 0, 0]

rv = reduce(lambda a, b: bool(a and b), mylist)
rv

False

In [ ]:
rv = reduce(lambda a,b : bool(a | b), mylist)

In [ ]:
rv

True

In [ ]:
a = sorted(mylist)

In [ ]:
a

[0, 0, 0, 0, 1]

In [ ]:
t1 = ('abcz', 'xyza', 'bas', 'arif','shuuu')

rv = sorted(t1)

print("Sorted tuple: ", rv)
print("Original tuple remains as such: ", t1)

Sorted tuple:  ['abcz', 'arif', 'bas', 'shuuu', 'xyza']
Original tuple remains as such:  ('abcz', 'xyza', 'bas', 'arif', 'shuuu')


In [ ]:
def last(s):
  return s[-1]

t = ['abc','aba','vcx','yreiw']

d = sorted(t, key=last)

In [ ]:
d

['aba', 'abc', 'yreiw', 'vcx']

In [ ]:
t1 = ('abcz', 'xyza', 'bas', 'arif')

rv = sorted(t1, key = lambda x : x[-1])

print("Sorted tuple: ", rv)
print("Original tuple remains as such: ", t1)

Sorted tuple:  ['xyza', 'arif', 'bas', 'abcz']
Original tuple remains as such:  ('abcz', 'xyza', 'bas', 'arif')


In [ ]:
mylist = [(4, 30), (6, 15), (1, 25), (9, 8)]

def func(item):
    return item[-1]

mylist_sorted = sorted(mylist, key = func)

mylist_sorted

[(9, 8), (6, 15), (1, 25), (4, 30)]

In [ ]:
l1 = [1,2,3,4,5]
l2 = [2,6,7,8]


z = zip(l1,l2)

e = list(z)

In [ ]:
e

[(1, 2), (2, 6), (3, 7), (4, 8)]

In [ ]:
mylist = ['banana', 'mango', 'grapes']
a = iter(mylist)
a

In [ ]:
next(a)


'mango'

In [ ]:
def mygenerator():
    print('First item')
    yield 10

    print('Second item')
    yield 20

    print('Last item')
    yield 30

In [ ]:
gen = mygenerator()

In [ ]:
next(gen)

Second item


20

In [ ]:
def gencubes(n):
    for num in range(n):
        yield num**3
for x in gencubes(5):
    print(x)

0
1
8
27
64


In [ ]:
gencubes(4)

<generator object gencubes at 0x7fc0ae05e0b0>

In [ ]:
listA = [1,3,3,4,5,5,6,6,7,8]
listB = []

for a in listA:
  if(a%2==0):
    listB.append(a)
print(listB)

[4, 6, 6, 8]


In [ ]:
listA = [1, 5, 8, 3, 2]
listB = [i for i in listA if i % 2 == 0]
print(listB)

[8, 2]


In [ ]:
def myfunc(nam):
    nam = "Arif Butt"

a = "Kakamanna"
print("Before calling: ", a)

rv = myfunc(a)
print("After calling: ", a)

Before calling:  Kakamanna
After calling:  Kakamanna


In [ ]:
def myfunc(x, y, z):
    x = x + 1
    y = y + 1
    z = z + 1

a = 10
b = 20
c = 30

myfunc(a, b, c)

print(a, b, c)

10 20 30


In [ ]:
# Tuples are mutable: proof of concept
def func1(t1):
    t1[2] = 'x'
    
mytuple = ('a', 'b', 'c', 'd', 'e', 'f')
print("Before calling: ", mytuple)

func1(mytuple)
print("After calling: ", mytuple)

Before calling:  ('a', 'b', 'c', 'd', 'e', 'f')


TypeError: ignored

In [ ]:
# Function with default arguments
def display(name = 'kakamanna', age = 35):
   print ("Name: ", name, ", Age: ", age)
   return;

# calling a function with both arguments (order matters)
display("Arif Butt", 51)

# calling a function with one argument only (the default value of age will be printed)
display("Mujahid Butt" )

Name:  Arif Butt , Age:  51
Name:  Mujahid Butt , Age:  35


In [ ]:
# Function calling with key word arguments
def display(name, age):
   print ("Name: ", name, ", Age: ", age)
   return;

# Sequence/order of arguments matter
display(25, "Arif Butt")

Name:  25 , Age:  Arif Butt


In [ ]:
def my_function(*args):   # Whatever is passed to this function, it will create an iterable out of it
    print(type(args))

my_function('arif','rauf')
print("\n")

<class 'tuple'>




In [ ]:
# Example: Passing variable number of arguments to a function
def my_function(*args):   # Whatever is passed to this function, it will create an iterable out of it
    for i in args:        # We can use the iter() and next() function to iterate through the iterable
        print(i, end=' ')

my_function()
my_function('arif','rauf')
print("\n")

my_function(1, 2, 3, 4, 5, 6, 7, 8)
print("\n")

my_function(5, 2.5, 9)

arif rauf 

1 2 3 4 5 6 7 8 

5 2.5 9 

In [ ]:
def myfunc(**kwargs):
    # Iterating over the key:value pairs of kwargs dictionary
    for arg in kwargs.items():
        print(arg)

        
myfunc(a = "Learning", b = 'Is', c = 'Fun')

('a', 'Learning')
('b', 'Is')
('c', 'Fun')


In [ ]:
def myfunc(**kwargs):
    result = ""
    # Iterating over the values only of kwargs dictionary
    for arg in kwargs.keys():
        print(arg)

myfunc(a = "Learning", b = 'Is', c = 'Fun', d ='with', e='Arif')


a
b
c
d
e


In [ ]:
def greet(**kwargs):
    print('Hello, ', kwargs['fname'],  kwargs['mname'], kwargs['lname'])

greet(lname='Butt', fname='Muhammad', mname= 'Arif')

Hello,  Muhammad Arif Butt


In [ ]:
def outerFunction(): 
    name = 'Arif'
    def innerFunction():
        print(name) 
    innerFunction() 
    
outerFunction() 

Arif


In [ ]:
def f1():
    cc = 1234      # cc is local variable to f1()
    def f2():
        cc = 4321  # cc is local variable to f2()
        print("Inside the f2() function: cc = ", cc)
    f2()
    print("Inside the f1() function: cc = ", cc)


f1()

Inside the f2() function: cc =  4321
Inside the f1() function: cc =  1234


In [ ]:
def len(x):
    return 54

x = len('Data Science')    
print(x)

54


In [ ]:
# Example:
c = 1234         # c is a global variable
def my_function():
    global c 
    c = c + 1   # Updating global variable inside function
    print("Value of variable 'c' inside function: ", c)

my_function()
print("Value of variable 'c' outside function: ", c)

Value of variable 'c' inside function:  1235
Value of variable 'c' outside function:  1235


In [ ]:
# Example 2: To update a nonlocal variable inside the inner function, you use the nonlocal keyword
def f1():
    a = 1234
    def f2():
        nonlocal a
        a = a + 1
        print("Inside the f2() function: a = ", a)
    f2()
    print("Inside the f1() function: a = ", a)


f1()

Inside the f2() function: a =  1235
Inside the f1() function: a =  1235


In [ ]:
x = 5
print(x, id(x))
def number():
    x = 3
    print(x, id(x))
    def f1():
        nonlocal x
        x = x * 5
        print(x, id(x))
    f1()
def numb():
    global x
    x = x * 5
    print(x, id(x))
number()
numb()    
print(x, id(x))

5 9793216
3 9793152
15 9793536
25 9793856
25 9793856


In [ ]:
import numpy as np
arr1 = np.arange(12)
arr2 = np.reshape(arr1,(4,3),order='F')
print(arr2)

arr3 = np.arange(16).reshape(4,4)
print(np.split(arr1, [1,3], axis=0))

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[array([0]), array([1, 2]), array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])]


In [ ]:
a = np.random.randint(low=1, high=10, size=(4,4))

In [ ]:
a

array([[4, 6, 2, 2],
       [1, 6, 1, 9],
       [2, 1, 9, 7],
       [1, 2, 8, 7]])

In [ ]:
print(np.split(a,[1,3],axis=1))

[array([[4],
       [1],
       [2],
       [1]]), array([[6, 2],
       [6, 1],
       [1, 9],
       [2, 8]]), array([[2],
       [9],
       [7],
       [7]])]


In [ ]:
arr3 = np.arange(16).reshape(4,4)
print(arr3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:

print(np.split(arr3, [1,3], axis=1))

[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [ ]:
arr = np.arange(5,95,5).reshape(3,2,3)
print(arr)
print(arr[-3])
print(arr[-1, 1:3])
print(arr.strides)

[[[ 5 10 15]
  [20 25 30]]

 [[35 40 45]
  [50 55 60]]

 [[65 70 75]
  [80 85 90]]]
[[ 5 10 15]
 [20 25 30]]
[[80 85 90]]
(48, 24, 8)


In [ ]:
arr1 = np.array([2,5,1])
arr2 = np.array([3,6,2])
arr3 = np.vstack((arr1, arr2))
arr4 = np.hstack((arr1, arr2))
arr5 = np.stack((arr1, arr2), axis = 1)
print (arr3)
print (arr4)
print (arr5)

[[2 5 1]
 [3 6 2]]
[2 5 1 3 6 2]
[[2 3]
 [5 6]
 [1 2]]


In [ ]:
import numpy as np

arrz = np.array([2,5,9,3,8])
def harmonic_mean(arr):
    return len(arr) / np.sum(1/arr)

In [ ]:
harmonic_mean(arrz)

42.5382932166302

In [ ]:
import scipy 
from scipy import stats
arr = np.array([2,5,9,3,8,10])
rv1 = scipy.stats.hmean(arr)

In [ ]:
rv1

4.381338742393509

In [ ]:
a = len(arr) / np.sum(1/arr)

In [ ]:
a

39.43204868154158

In [ ]:
a = np.arange(1, 51)




In [ ]:
b = a.reshape(5,2,5)

In [ ]:
b

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50]]])

In [ ]:
b.ndim

3

In [ ]:
a = np.arange(3,13).reshape(2,5)

In [ ]:
a

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])

In [ ]:
arr1 = np.array([3,4,5,6,7])

In [ ]:
arr2 = np.array([9,10])

In [ ]:
arr3 = np.append(arr1,arr2)

In [ ]:
arr3

array([ 3,  4,  5,  6,  7,  9, 10])

In [ ]:
print(id(arr1))
print(id(arr2))

140465407668112
140465407261936


In [ ]:
arr1 = np.random.randint(low = 1, high = 10, size = (3,3))
print("arr1 = \n", arr1)

arr1 = 
 [[6 9 5]
 [3 6 6]
 [5 8 8]]


In [ ]:
arr2 = np.array([[12],[10],[3]])

In [ ]:
arr3  = np.append(arr1,arr2, axis = 0)

In [ ]:
arr3

array([[ 6,  9,  5],
       [ 3,  6,  6],
       [ 5,  8,  8],
       [12, 11, 10]])

In [ ]:
arr3  = np.append(arr1,arr2, axis = 1)

In [ ]:
arr3

array([[ 6,  9,  5, 12],
       [ 3,  6,  6, 10],
       [ 5,  8,  8,  3]])

In [ ]:
arr1 = np.random.randint(low = 1, high = 100, size = 5)
print("arr1 = ", arr1)

arr1 =  [78 77 20 71 46]


In [ ]:
# Initialize a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Initialize the array to be appended
array_to_append = np.array([[[9, 10], [11, 12]]])

# Concatenate the arrays along the first axis
result = np.concatenate((array_3d, array_to_append), axis=0)

print(result)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
arr = np.random.randint(1, 10, size=(3, 4, 2))
new_arr = np.random.randint(1, 10, size=(3, 2))

result = np.concatenate((arr, new_arr[:, np.newaxis, :]), axis=1)

In [ ]:
result

array([[[1, 1],
        [5, 5],
        [9, 5],
        [1, 4],
        [4, 7]],

       [[5, 8],
        [7, 4],
        [2, 6],
        [8, 4],
        [2, 3]],

       [[1, 7],
        [3, 6],
        [9, 1],
        [6, 7],
        [7, 1]]])

In [ ]:
arr1 = np.random.randint(low = 1, high = 10, size = (3,4))
print("arr1 = \n", arr1)

arr1 = 
 [[2 5 1 3]
 [7 5 2 7]
 [2 9 1 8]]


In [ ]:
arr2 = np.insert(arr1, 2, [55, 66,55,66],axis = 0)
print("After insert:")
print("arr1 = \n", arr1)
print("arr2 = ", arr2)

After insert:
arr1 = 
 [[2 5 1 3]
 [7 5 2 7]
 [2 9 1 8]]
arr2 =  [[ 2  5  1  3]
 [ 7  5  2  7]
 [55 66 55 66]
 [ 2  9  1  8]]


In [ ]:
arr2 = np.insert(arr1, 2, 55, axis=1)
print("After insert:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

After insert:
arr1 = 
 [[2 5 1 3]
 [7 5 2 7]
 [2 9 1 8]]
arr2 = 
 [[ 2  5 55  1  3]
 [ 7  5 55  2  7]
 [ 2  9 55  1  8]]


In [ ]:
arr2 = np.insert(arr1, 2, [55, 66, 77, 88], axis=0)
print("After insert:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

After insert:
arr1 = 
 [[2 5 1 3]
 [7 5 2 7]
 [2 9 1 8]]
arr2 = 
 [[ 2  5  1  3]
 [ 7  5  2  7]
 [55 66 77 88]
 [ 2  9  1  8]]


In [ ]:
arr1 = np.random.randint(low = 1, high = 10, size = 5)
print("arr1 = ", arr1)
# You can delete a scalar value from a specific index
arr2 = np.delete(arr1, 3)
print("After delete:")
print("arr1 = ", arr1)
print("arr2 = ", arr2)

arr1 =  [6 5 3 5 2]
After delete:
arr1 =  [6 5 3 5 2]
arr2 =  [6 5 3 2]


In [ ]:
arr1 = np.random.randint(low = 1, high = 100, size = 10)
print("arr1 = ", arr1)
# You can delete a list of values in between array elements from specific indices
arr2 = np.delete(arr1, [2,5])
print("After delete:")
print("arr1 = ", arr1)
print("arr2 = ", arr2)

arr1 =  [68 92 78 43 31  2 12 28 37 10]
After delete:
arr1 =  [68 92 78 43 31  2 12 28 37 10]
arr2 =  [68 92 43 31 12 28 37 10]


In [ ]:
arr1 = np.random.randint(low = 1, high = 10, size = (4,4))
print("arr1 = \n", arr1)
arr2 = np.delete(arr1, 2, axis=0)
print("After delete:")
print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

arr1 = 
 [[1 4 2 5]
 [8 7 7 5]
 [6 6 2 5]
 [7 7 9 7]]
After delete:
arr1 = 
 [[1 4 2 5]
 [8 7 7 5]
 [6 6 2 5]
 [7 7 9 7]]
arr2 = 
 [[1 4 2 5]
 [8 7 7 5]
 [7 7 9 7]]


In [ ]:
arr1 = np.random.randint(low = 1, high = 10, size = 10)

# Creating a copy using assignment operator, both variables point at the same array
arr2 = arr1

print("arr1 = ", arr1)
print("arr2 = ", arr2)
print(id(arr1))
print(id(arr2))

arr1 =  [9 5 8 1 7 2 4 8 3 6]
arr2 =  [9 5 8 1 7 2 4 8 3 6]
140465407474448
140465407474448


In [ ]:
arr2[2] = 55
print("arr1 = ", arr1)
print("arr2 = ", arr2)

arr1 =  [ 9  5 55  1  7  2  4  8  3  6]
arr2 =  [ 9  5 55  1  7  2  4  8  3  6]


In [ ]:
x = -11
y = 4

# Output: x + y 
print('x + y =',x+y)

# Output: x - y 
print('x - y =',x-y)

# Output: x * y 
print('x * y =',x*y)

# Output: x / y 
print('x / y =',x/y)

# Floor Division: Output: x // y 
print('x // y =',x//y)

x + y = -7
x - y = -15
x * y = -44
x / y = -2.75
x // y = -3


In [ ]:
#Bitwise operators in Python
x = -10   # 00001010
y = 4    # 00000100


# Bitwise and
print('x & y is',x&y)

# Bitwise or
print('x | y is',x|y)

# Bitwise not
print('~x is',~x)

# Bitwise XOR
print('x^y is',x^y)

# Bitwise right shift
print('x>>3 is',x>>3)

# Bitwise left shift
print('x<<3 is',x<<3)

x & y is 4
x | y is -10
~x is 9
x^y is -14
x>>3 is -2
x<<3 is -80


In [ ]:
a = 5
b = 5.0

print(a is b)
print(a==b)

False
True


In [ ]:
str = 'Python Programming is fun'
print('str = ', str)

#access first index
print('str[0] = ', str[6])

# Negative indices start from the opposite end of the string. Hence, -1 index corresponds to the last character
print('str[-1] = ', str[-1])

#access second last index
print('str[-2] = ', str[-2])

str =  Python Programming is fun
str[0] =   
str[-1] =  n
str[-2] =  u


In [ ]:
str1 = 'ArifButt'

#str1[5] = 'c'

print(id(str1))

#assigning a new value is valid
str1 = 'python'

print(id(str1))

140465406503152
140466022661360


In [ ]:
buffer ="    hello world, this is       Arif Butt      "
rv = buffer.strip()
print(rv)

hello world, this is       Arif Butt


In [ ]:
str1 = 'Learning is fun'    #this is a string
list1 = str1.split(' ')
list1

['Learning', 'is', 'fun']

In [ ]:
t1 = ('a','b','c','d','e','f','g','h','i')
t1[-1]

'i'

In [ ]:
a = range(10)


In [ ]:
a

range(0, 10)

In [ ]:
print(a)

range(0, 10)


In [ ]:
age = 19

In [ ]:
a = 'child' if age<=14 else 'adult'

In [ ]:
a

'adult'

In [ ]:
a_number = 3
parity = 'even' if a_number % 2 == 0 else 'odd'
print('The number {} is {}.'.format(a_number, parity))


The number 3 is odd.


In [ ]:
num = 0

while num<=7:
  num = num + 1
  print("hello" , num)

print("bye")

hello 1
hello 2
hello 3
hello 4
hello 5
hello 6
hello 7
hello 8
bye


In [ ]:
num = 0

while num<=7:
    print("hello" , num)
    num = num + 1

print("bye")

hello 0
hello 1
hello 2
hello 3
hello 4
hello 5
hello 6
hello 7
bye


In [ ]:
e = int(input('enter a number: '))
sum = 0
i = 1

while(i<=e):
  sum = sum + i
  i = i + 1
print(sum)

enter a number: 2
3


In [ ]:
list1 = ['Learning', 'is', 'fun', 'with', 'Arif Butt']
ctr = 0
while(ctr < len(list1)):
    print(list1[ctr])
    ctr += 1

print(list1)

Learning
is
fun
with
Arif Butt


IndexError: ignored

In [ ]:
mylist = ['banana', 'mango', 'grapes']


In [ ]:
for i in mylist:
  print(i)

banana
mango
grapes


In [ ]:
# Creating tuple iterator from a tuple iterable using the iter() method
mytuple = ('banana', 'mango', 'grapes')
iterator_mytuple = iter(mytuple)
iterator_mytuple

In [ ]:
next(iterator_mytuple)

'banana'

In [ ]:
# Creating dictionary item-iterator from a dictionary iterable using the iter() method
mydict = {1:'banana', 2:'mango', 3:'grapes'}
iterator_dictitems = iter(mydict.items())
iterator_dictitems

In [ ]:
next(iterator_dictitems)

(1, 'banana')

In [ ]:
for i in ("Be Happy"):
    print(i)

B
e
 
H
a
p
p
y


In [ ]:
# Example 4: Iterate a string using for loop and count the count of a specific character
word = "Welcome to Learning with Arif Butt."
count = 0
for character in word:
    if character == 'e':
        count = count+1
print(count)

3


In [ ]:
list(range(10,15))

[10, 11, 12, 13, 14]

In [ ]:
friends = ['Rauf','Arif', 'Maaz', 'Hadeed', 'Muhahid', 'Mohid']

for i in range(len(friends)):  # Remember the len() function returns 6 in this scenario
    print('The value at position {} is {}.'.format(i, friends[i]))

The value at position 0 is Rauf.
The value at position 1 is Arif.
The value at position 2 is Maaz.
The value at position 3 is Hadeed.
The value at position 4 is Muhahid.
The value at position 5 is Mohid.


IndexError: ignored

In [ ]:
mylist = ['arif', 'hadeed', 'mujahid']
rv = enumerate(mylist)
print(type(rv))
mylist = ['arif', 'hadeed', 'mujahid']
print(list(enumerate(mylist)))

<class 'enumerate'>
[(0, 'arif'), (1, 'hadeed'), (2, 'mujahid')]


In [ ]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]

newlist = [fruit for fruit in fruits if ("a" in fruit)]

print(newlist)

['apple', 'banana', 'mango']
