In [1]:
import sys
!{sys.executable} -m pip install numpy

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
arr = np.array(3)

In [5]:
print(arr)

3


In [6]:
mylist = [1, 4, 2, 5, 3]
arr = np.array(mylist, dtype=np.uint8)
arr = np.array([1, 4, 2, 5, 3], dtype=np.uint32)

print("array: ", arr)
print("arr.ndim: ", arr.ndim)   # get number of dimensions
print("arr.shape: ", arr.shape) # This is 1-D array having 5 columns, so return a tuple with one element
print("arr.size: ", arr.size)   # get total number of elements
print("arr.dtype: ", arr.dtype) # get data type, default is what is minimum required to hold the max size element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory (2*5=10)

print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array:  [1 4 2 5 3]
arr.ndim:  1
arr.shape:  (5,)
arr.size:  5
arr.dtype:  uint32
arr.itemsize:  4
arr.nbytes:  20
arr.data:  <memory at 0x000001D52C3C8D00>
arr.strides:  (4,)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [35]:
arr1 = np.random.rand(3,2)*10
print(arr1)

[[7.98513914 6.39439603]
 [9.13448513 4.94220169]
 [6.03873509 1.9348596 ]]


In [36]:
print("arr1.nbytes: ", arr1.nbytes)

arr1.nbytes:  48


In [37]:
np.__version__

'1.24.1'

In [10]:

arr = np.array([1, 4, 2, 5, 3], dtype=np.uint8)

print("array: ", arr)
print("arr.ndim: ", arr.ndim)   # get number of dimensions
print("arr.shape: ", arr.shape) # This is 1-D array having 5 columns, so return a tuple with one element
print("arr.size: ", arr.size)   # get total number of elements
print("arr.dtype: ", arr.dtype) # get data type, default is what is minimum required to hold the max size element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory (2*5=10)

print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)


array:  [1 4 2 5 3]
arr.ndim:  1
arr.shape:  (5,)
arr.size:  5
arr.dtype:  uint8
arr.itemsize:  1
arr.nbytes:  5
arr.data:  <memory at 0x000001D52C3C8D00>
arr.strides:  (1,)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [11]:
list = [
    [1,2,3,3,4],
    [3,3,5,3,3],
    [4,3,5,25,1],
    [3,4,4,4,3]
]

In [40]:
arr2 = np.array(list, dtype=np.uint64)
arr2

array([[ 1,  2,  3,  3,  4],
       [ 3,  3,  5,  3,  3],
       [ 4,  3,  5, 25,  1],
       [ 3,  4,  4,  4,  3]], dtype=uint64)

In [38]:
arr2.strides

(40, 8)

In [14]:
arr2.shape

(4, 5)

In [15]:
arr2.nbytes

160

In [41]:
arr2.ndim

2

In [17]:
arr3 = np.arange(1,4,1)

In [18]:
print(arr3)

[1 2 3]


In [45]:
arrr = np.random.randint(low= 1, high = 20, size=(4,3,3), dtype=np.uint32)

In [46]:
print(arrr)

[[[10 16  2]
  [ 8  2 14]
  [ 7 16 14]]

 [[15  7 19]
  [11  5  7]
  [13 10 13]]

 [[13 17 12]
  [10  6 11]
  [13  3  4]]

 [[19 14 15]
  [ 2  5  8]
  [11 14  4]]]


In [47]:
arrr.strides

(36, 12, 4)

In [48]:
print(arrr[:,1:3,1:3])

[[[ 2 14]
  [16 14]]

 [[ 5  7]
  [10 13]]

 [[ 6 11]
  [ 3  4]]

 [[ 5  8]
  [14  4]]]


In [49]:
arr4 = np.random.randint(low= 1, high = 20, size=(5,5), dtype=np.uint32)

In [50]:
arr4

array([[ 1, 15, 18, 10,  2],
       [ 2, 18, 13,  3,  8],
       [16, 13, 12,  8,  9],
       [ 6, 18, 16,  4, 10],
       [ 7,  2, 10,  1, 15]], dtype=uint32)

In [25]:
row_wanted = np.array([False,True,True,True,False])

In [26]:
column_wanted = np.array([False,True,True,True,False])

In [27]:
arr5 = arr4[1:4,1:4]

In [28]:
arr5

array([[ 5,  5,  7],
       [13,  1, 12],
       [19,  9,  5]], dtype=uint32)

In [29]:
arrr2 = arr4[ 1 : -2,  1 : -2 ]



In [30]:
arrr2

array([[ 5,  5],
       [13,  1]], dtype=uint32)

In [31]:
arr6 = np.arange(8).reshape(2,2,2)

In [32]:
arr6

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [33]:
arr7 = np.swapaxes(arr6,0,1)

In [34]:
arr7

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

In [53]:
a = "faouerbchtniaeauiaxcuzsucayrtnianydaut"
print(a[-4:3:-3])
print(10 + (-3 << 2))

datascience
-2


In [78]:
-25>>3

-4

In [81]:
-29>>2

-8

In [80]:
-10<<2

-40