<a href="https://colab.research.google.com/github/shumyyla/test/blob/master/stacking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1 = np.random.randint(low = 1, high = 10, size = 4)
arr2 = np.random.randint(low = 1, high = 10, size = 4)
print("arr1 = ", arr1)
print("arr2 = ", arr2)
  
# Stacking two 1-D arrays along axis 0 using stack()
arr3 = np.stack((arr1, arr2), axis = 0)
print ("\n np.stack(arr1, arr2, axis=0):\n ", arr3)
# Stacking the two 1-D arrays using row_stack()
arr4 = np.row_stack((arr1, arr2))
print ("\n np.row_stack(arr1, arr2)):\n ", arr4)
  

# Stacking two 1-D arrays along axis 1 using stack()
arr5 = np.stack((arr1, arr2), axis = 1)
print ("\n np.stack((arr1, arr2), axis=1):\n ", arr5)
# Stacking the two 1-D arrays using column_stack()
arr6 = np.column_stack((arr1, arr2))
print ("\n np.column_stack(arr1, arr2):\n ", arr6)


arr1 =  [4 5 9 1]
arr2 =  [2 2 3 9]

 np.stack(arr1, arr2, axis=0):
  [[4 5 9 1]
 [2 2 3 9]]

 np.row_stack(arr1, arr2)):
  [[4 5 9 1]
 [2 2 3 9]]

 np.stack((arr1, arr2), axis=1):
  [[4 2]
 [5 2]
 [9 3]
 [1 9]]

 np.column_stack(arr1, arr2):
  [[4 2]
 [5 2]
 [9 3]
 [1 9]]


In [ ]:
import numpy as np
arr1 = np.array([[4,3,1],[5,6,2]])
arr2 = np.array([[5,1,8],[3,9,1]])

print("arr1 = \n", arr1)
print("arr2 = \n", arr2)

  
# Stacking the two arrays along last axis
arr3 = np.stack((arr1, arr2), axis = -1)
print ("\n np.stack((arr1, arr2), axis=-1):\n ", arr3)
print("shape of arr3:", arr3.shape)

arr1 = 
 [[4 3 1]
 [5 6 2]]
arr2 = 
 [[5 1 8]
 [3 9 1]]

 np.stack((arr1, arr2), axis=-1):
  [[[4 5]
  [3 1]
  [1 8]]

 [[5 3]
  [6 9]
  [2 1]]]
shape of arr3: (2, 3, 2)


In [ ]:
# create an array of float type
arr1 = np.random.randint(low = 1, high = 10, size = 22)
print("arr1:\n",arr1)

# The array_split() will not flag an error if size is not a factor of array size (will manage)
#print("\nSub-arrays: \n", np.array_split(arr1, 4))


arr1:
 [1 4 3 5 3 4 7 4 7 6 5 7 6 5 2 4 9 2 5 6 3 9]


In [ ]:


# The array_split() will not flag an error if size is not a factor of array size (will manage)
print("\nSub-arrays: \n", np.array_split(arr1, 3))



Sub-arrays: 
 [array([1, 4, 3, 5, 3, 4, 7, 4]), array([7, 6, 5, 7, 6, 5, 2]), array([4, 9, 2, 5, 6, 3, 9])]


In [ ]:
# create an array of float type with 4 rows and 4 columns with sequential values from 0 to 15
arr1 = np.arange(16.0).reshape(4,4)
# print array
print("arr1:\n",arr1)
print("shape: ", arr1.shape)
# horizontally split array into 2 subarrays
print("\nSub-arrays: \n", np.hsplit(arr1, 2))

arr1:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
shape:  (4, 4)

Sub-arrays: 
 [array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]


In [ ]:
import numpy as np
arr1 = np.array([2,5,1])
arr2 = np.array([3,6,2])
arr3 = np.column_stack((arr1, arr2))
arr9 = np.row_stack((arr1,arr2))
arr4 = np.vstack((arr1, arr2))
arr5 = np.hstack((arr1, arr2))
arr6 = np.stack((arr1, arr2), axis = 1)

arr = np.stack((arr1, arr2), axis = 0)

print ("arr3: ", arr3)
print ("arr4: ", arr5)
print ("arr6: ", arr6)
print ("vstack: ", arr4)

print("row stack",arr9)


print("np.stack axis 0", arr)

arr3:  [[2 3]
 [5 6]
 [1 2]]
arr4:  [2 5 1 3 6 2]
arr6:  [[2 3]
 [5 6]
 [1 2]]
vstack:  [[2 5 1]
 [3 6 2]]
row stack [[2 5 1]
 [3 6 2]]
np.stack axis 0 [[2 5 1]
 [3 6 2]]
